#makefile for nekoware based SDL Program

INCLUDE = -I/usr/include -I/usr/nekoware/include/SDL
LIBDIR  = -L/usr/nekoware/lib -L/usr/lib32/

COMPILERFLAGS =  `sdl-config --cflags --libs`

CC = /usr/nekoware/bin/gcc
CFLAGS = $(COMPILERFLAGS) $(INCLUDE)
LIBRARIES = -lSDL

all:  soccer

soccer : soccer.o
	$(CC) $(CFLAGS) -o soccer $(LIBDIR) soccer.o $(LIBRARIES)  
clean:
	rm soccer *.o


