# LINUX makefile for SDL based IRIX Soccer Game

INCLUDE = -I/usr/include -I/usr/include/SDL
LIBDIR  =  

COMPILERFLAGS =  `sdl-config --cflags --libs`

CC = gcc
CFLAGS = $(COMPILERFLAGS) $(INCLUDE)
LIBRARIES = -lSDL

all:  soccer

soccer : soccer.o
	$(CC) $(CFLAGS) -o linux_soccer $(LIBDIR) soccer.o $(LIBRARIES)  
clean:
	rm soccer *.o


